{% set name = "anyioutils" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f370137137884aeb19def8ca2af162d814ef193c746ce7cbd0677ed8d38f2364

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - anyio >=4.8.0,<5.0.0
    - exceptiongroup

test:
  imports:
    - anyioutils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/davidbrochart/anyioutils
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Utility classes and functions for AnyIO
  dev_url: https://github.com/davidbrochart/anyioutils

extra:
  recipe-maintainers:
    - davidbrochart
