{% set name = "anyioutils" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7d167cbe82678351fba5717a5abb16c4ddca59ebb7b2afe598acc20214f763a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - anyio >=4.8.0,<5.0.0
    - outcome >=1.3.0,<2.0.0
    - exceptiongroup
    - typing_extensions

test:
  imports:
    - anyioutils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/davidbrochart/anyioutils
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Utility classes and functions for AnyIO
  dev_url: https://github.com/davidbrochart/anyioutils
  doc_url: https://davidbrochart.github.io/anyioutils

extra:
  recipe-maintainers:
    - davidbrochart
