{% set name = "anyioutils" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 69800442408763121e35d5466df09bf2e397e65499e57f333cd6ca5a9051355f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - anyio

test:
  imports:
    - anyioutils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/davidbrochart/anyioutils
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Utility classes and functions for AnyIO
  dev_url: https://github.com/davidbrochart/anyioutils

extra:
  recipe-maintainers:
    - davidbrochart
